name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Apt update
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install libgl1-mesa-dev xorg-dev libasound2-dev

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Benchmark
        run: go test -benchmem -run=^$ -bench . github.com/guigzzz/GoGB/backend
